services:
  mysqldb: 
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./dbinit/procedures.sql:/docker-entrypoint-initdb.d/02-procedures.sql
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      SERVICE:TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
    
networks:
  internalnet:
    driver: bridge

volumes:
  mysql_data:
